### PR TITLE
Added GitHub Gist link to installation tutorial

### PR DESCRIPTION
**Pull request by santurini**
Thought it would be nice to help during the installation procedure with a step-by-step tutorial.

### CODE REVIEW

**Comment by laekov** [comment]
Thanks for the document! Why don't we directly put it directly in README.md? If it is too long to be presented in the homepage, we can also put it in `docs/installation-guide.md`.

**Comment by santurini** [comment]
Something like this?

**Comment by laekov** [comment]
Well, this looks too long. #154 looks better. Let's work on that.

**Comment by santurini** [comment]
I agree, maybe just add a pointer to the docs in the README as in the previous commit.

**Pull request closed without merging**
