### PR TITLE
Compatibility to torch v1.10.0

### PR DESCRIPTION
**Pull request by laekov**

### CODE REVIEW

**Comment by Tengxu-Sun** [comment]
cool, i'll have a try! thx!

**Comment by Tengxu-Sun** [comment]
Btw, you add `-DUSE_C10D_NCCL`, will this have any affect on fastmoe usage.

**Comment by laekov** [comment]
> Btw, you add `-DUSE_C10D_NCCL`, will this have any affect on fastmoe usage.

No change of users' code is required. This modification only involves PyTorch's header file, where an additional macro is introduced to enable the `ProcessGroupNCCL` class.

**Comment by Tengxu-Sun** [comment]
> > Btw, you add `-DUSE_C10D_NCCL`, will this have any affect on fastmoe usage.
> 
> No change of users' code is required. This modification only involves PyTorch's header file, where an additional macro is introduced to enable the `ProcessGroupNCCL` class.

ok, thanks a lot.

**Review by TiagoMAntunes — APPROVED** [review]

**Pull request merged**
